### PR TITLE
chore: Upgrade deps and fix minor changes from upgrades

### PR DESCRIPTION
**Pull request by HexSleeves**
Bumping wgpu was the main focus.  Couple of changes in the texture file from bumping. Just switched from `NonZeroU32` to `u32`

### CODE REVIEW

**Comment by hakolao** [comment]
Thx, side question: what plugin modifies your toml formatting?

**Comment by HexSleeves** [comment]
Oh i apologize. I always forget to disable auto-formatting when working in other repositories. I can fix if you would prefer.

The plugin comes from vscode. https://marketplace.visualstudio.com/items?itemName=tamasfe.even-better-toml

**Comment by hakolao** [comment]
better to fix it :). I like the non modified toml. Until I figure out a plugin for CLion.

**Comment by HexSleeves** [comment]
Sounds good :) should be updated now! appreciate your work on this

**Comment by hakolao** [comment]
Just realized wgpu 0.16 may not work with egui (optional with this), so that should be updated too. I dont mind a github rev version for egui.

did you try running all the examples?

I’ll be able to better test & merge after monday, pretty busy this weekend :)

**Comment by HexSleeves** [comment]
You are right, the egui is still on wgpu 16 which breaks.

Running all the examples shows no discrepancies, except for egui example.

**Pull request merged**
